### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined at module.exports 

### ISSUE THREAD

**Issue by CitizenXC** [AtomLinter/linter-sass-lint#12]
Using Atom 1.4.0 on OSX 10.10.5.  When I save a scss.erb file I get the following error every time:
```
TypeError: Cannot read property 'toString' of undefined at module.exports (/Users/dwheeler/.atom/packages/linter-sass-lint/node_modules/sass-lint/lib/groot.js:25:89) at Function.sassLint.lintText (/Users/dwheeler/.atom/packages/linter-sass-lint/node_modules/sass-lint/index.js:36:13) at /Users/dwheeler/.atom/packages/linter-sass-lint/node_modules/sass-lint/index.js:91:21 at Array.forEach (native) at Function.sassLint.lintFiles (/Users/dwheeler/.atom/packages/linter-sass-lint/node_modules/sass-lint/index.js:90:9) at Object.provider.lint (/Users/dwheeler/.atom/packages/linter-sass-lint/lib/main.coffee:87:28) at promises.push.Promise.then._this.emitter.emit.linter (/Users/dwheeler/.atom/packages/linter/lib/linter-registry.js:63:26) at /Users/dwheeler/.atom/packages/linter/lib/linter-registry.js:62:23 at Set.forEach (native) at LinterRegistry.lint (/Users/dwheeler/.atom/packages/linter/lib/linter-registry.js:60:18) at /Users/dwheeler/.atom/packages/linter/lib/linter.coffee:98:16 at Function.module.exports.Emitter.simpleDispatch (/Users/dwheeler/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14) at Emitter.module.exports.Emitter.emit (/Users/dwheeler/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28) at /Users/dwheeler/.atom/packages/linter/lib/editor-linter.js:30:20 at Function.module.exports.Emitter.simpleDispatch (/Users/dwheeler/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14) at Emitter.module.exports.Emitter.emit (/Users/dwheeler/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28) at TextBuffer.module.exports.TextBuffer.saveAs (/Users/dwheeler/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1067:27) at TextBuffer.module.exports.TextBuffer.save (/Users/dwheeler/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1037:19) at TextEditor.module.exports.TextEditor.save (/Users/dwheeler/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:602:26) at Pane.module.exports.Pane.saveItem (/Users/dwheeler/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:534:18) at Pane.module.exports.Pane.saveActiveItem (/Users/dwheeler/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:517:19) at Workspace.module.exports.Workspace.saveActivePaneItem (/Users/dwheeler/Downloads/Atom.app/Contents/Resources/app.asar/src/workspace.js:643:35) at atom-workspace.commandRegistry.add.core:save (/Users/dwheeler/Downloads/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:173:32) at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/dwheeler/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29) at /Users/dwheeler/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61 at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/dwheeler/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16) at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/dwheeler/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22) at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Users/dwheeler/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36) at HTMLDocument. (/Users/dwheeler/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

**Comment by Arcanemagus** [comment]
Does `sass-lint` work on that file from the terminal?

**Comment by DanPurdy** [comment]
Hi @CitizenXC could you please provide a little more information such as plugin version and sass-lint version being used and also even show the contents of that file and a screenshot of your project structure/tree. The plugin shouldn't be running against erb files and sass-lint relies on the scss or sass extensions to a file determine what style of Sass it should be parsing.. 

If you could provide some of those extra details I'd be able to gauge whether this is an issue with this plugin or something we need to fix in sass-lint itself..

Thanks!

**Comment by CitizenXC** [comment]
> sass-lint version being used

0.6.3

> the contents of that erb file

The erb file in question is a rails stylesheet named [project].scss.erb

   ```css
    <%= $variables %>

    input {
      line-height: 1em !important;
    }

    #ErrorWrapperPopup {
      background-color: #eb594f;
      border: solid 1px #bf2015;
      box-shadow: 0 1px 4px rgba(0, 0, 0, .6);
      float: right;
      margin-right: 10px;
      margin-top: 5px;
      width: 300px;
      z-index: 1;
    }

    .checkbox_spacing {
    	margin-top: 10px;
    }

    #ErrorWrapper.bulk_import {
      margin: 20px;
      max-width: 900px;
      position: relative;
      width: auto;
    }

    #s2id_new_public_identities {
      border: 0;
      border-radius: 0;

      .select2-choices {
        -webkit-box-shadow: none;
        box-shadow: none;

      }

      ul {
        background: none;
        border: 0;
      }

      .select2-search-field {
        display: none;
        border: 0;
      }
    }

    .no-search {
      display: none !important;
    }

    .or {
      float: left;
      padding: 7.5px 10px 5px;
      text-align: left;
      width: 40px;
    }

    .actionElement {
      padding: 2.5px;
    }

    #DeregistrationModal {
      display: none;

      h3 {
        font-weight: bold;
      }

      form .error {
        color: $errorColor;
        font-style: italic;
        padding: 5px 0;
      }
    }

    tr {
      &.recentlyUpdated {
        background: desaturate(lighten($successColor, 60%), 60%);
      }

      &.faded {
        -webkit-transition: background-color 1.5s ease-out;
        -moz-transition: background-color 1.5s ease-out;
        transition: background-color 1.5s ease-out;
        background: #fff;
      }
    }

    .hide_ppr {
      display: none;
    }
```

> a screenshot of your project structure/tree

-OverProject
--core
--engines
--products
---product
----app
-----assets
------stylesheets
(this is the best I can do w/ company restrictions)
