### ISSUE TITLE
Not sure what is wrong here...

### ISSUE THREAD

**Issue by mikeerickson** [AtomLinter/linter-sass-lint#121]
I am regularly receiving the following error.  

http://d.pr/i/191UW

As you can see by screenshot, the rule indeed exists in my `sass-lint.yml` file

**Comment by DanPurdy** [comment]
Hi @mikeerickson That rule doesn't exist in `Sass-lint`. So you need to remove it from your config. You might be looking at the wrong linter rules here? A list of all valid `Sass-lint` rules can be found at https://github.com/sasstools/sass-lint/tree/develop/docs/rules.

I'll close this but feel free to reply if you need any help.

**Comment by mikeerickson** [comment]
@DanPurdy Hey Dan, thanks for quick reply.  Is there an opinionated `sass-lint.yml` you start with?  May as well use something from creator to get started with.

**Comment by DanPurdy** [comment]
@mikeerickson no problem, by default sass-lint uses an internal config file which has all of the available rules in. Most are set to warnings and others are just turned off but it's a starting point at least. You can find it here https://github.com/sasstools/sass-lint/blob/develop/lib/config/sass-lint.yml

**Comment by mikeerickson** [comment]
@DanPurdy 

Hey Dan

Back to visiting this issue and I am not sure what to do about my situation.

If I call `sass-lint` from CLI as follows, it returns some 7 warnings (as expect)

```
$ sass-lint ./sass/**/*.sass -v -q
```

However, if I call it as 

```
$ sass-lint ./sass/**/*.sass
```

then no issues are shown (guess that makes sense)

====

Now, comes to `atom/linter-sass-lint`

I cant get it to throw any errors (or warnings) which matches the second operation outlined above.

Is there a way to pass the -v -q flags to `atom/linter-sass-lint` which I assume will trigger the same warnings as those returned from CLI

**Comment by mikeerickson** [comment]
@DanPurdy 

I _believe_ I have tracked down the issue.  I have a `.sass-lint.yml` file in my project.  With that file included, it seems to cause linter to show no errors (or warnings)

please find attached my `.sass-lint.yml` file.  What could be throwing the plugin for a loop? I am assuming it has something to do with the `include` items

```
options:
  formatter: stylish
files:
  include: './sass/**/*.s+(a|c)ss'
  ignore:
    - './sass/vendor/**/*.*'
    - './sass/_disabled/**/*.*'
    - './sass/modules/**/*.*'
rules:
  # Extends
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 1

  # Mixins
  mixins-before-declarations: 0 # 1

  # Line Spacing
  one-declaration-per-line: 1
  empty-line-between-blocks: 0 # 1
  single-line-per-selector: 1

  # Disallows
  no-attribute-selectors: 0
  no-color-keywords: 0 # 1
  no-color-literals: 0 # 1
  no-combinators: 0
  no-css-comments: 0 # 1
  no-debug: 1
  no-disallowed-properties: 0
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 1
  no-important: 1
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties: 1
  no-qualifying-elements: 1
  no-trailing-whitespace: 1
  no-trailing-zero: 1
  no-transition-all: 1
  no-universal-selectors: 0
  no-url-protocols: 1
  no-vendor-prefixes: 1
  no-warn: 1
  property-units: 0

  # Nesting
  force-attribute-nesting: 1
  force-element-nesting: 1
  force-pseudo-nesting: 1

  # Name Formats
  class-name-format: 1
  function-name-format: 1
  id-name-format: 0
  mixin-name-format: 1
  placeholder-name-format: 1
  variable-name-format: 0 # 1  // allow BEM style names

  # Style Guide
  attribute-quotes: 1
  bem-depth: 0
  border-zero: 1
  brace-style: 1
  clean-import-paths: 1
  empty-args: 1
  hex-length: 1
  hex-notation: 1
  indentation: 1
  leading-zero: 1
  nesting-depth: 1
  property-sort-order: 0 #1
  pseudo-element: 0 # 1
  quotes: 1
  shorthand-values: 1
  url-quotes: 1
  variable-for-property: 1
  zero-unit: 0 # 1

  # Inner Spacing
  space-after-comma: 1
  space-before-colon: 1
  space-after-colon: 1
  space-before-brace: 1
  space-before-bang: 1
  space-after-bang: 1
  space-between-parens: 1
  space-around-operator: 1

  # Final Items
  trailing-semicolon: 1
  final-newline: 1
```
