### ISSUE TITLE
Interpolation: #{} problems in property names

### ISSUE THREAD

**Issue by souzavitor** [AtomLinter/linter-sass-lint#13]
The plugin says: "Please check the validity of the block" when using an interpolation "#{}" in property names.
**Example:**
```scss
// file.scss
$attr: border;
p {
  #{$attr}-color: blue;
}
```
