### ISSUE TITLE
PropertySortOrder can't be disabled 

### ISSUE THREAD

**Issue by leon-yum** [AtomLinter/linter-sass-lint#185]
## New Issue information
I have the latest sass-lint installed and the linster-sass-lint package installed in atom.

In my **.sass-lint.yml** file I changed it to the following:

```
  PropertySortOrder:
    enabled: false
    ignore_unspecified: false
    min_properties: 2
    separate_groups: false
```

![screen shot 2017-09-18 at 2 20 23 pm](https://user-images.githubusercontent.com/30158970/30560170-a59596c2-9c7c-11e7-9477-c4f00b224eb4.png)

- Atom version: 1.20
- linter-sass-lint version: 1.8
- Global sass-lint version (if used): `"scss-lint": "^0.0.0"` would only let me install that
- Platform:
   - [*] OSX
- Expected behaviour:
- Actual behaviour / issue description:
