### ISSUE TITLE
Atom freezes on class-name-format option

### ISSUE THREAD

**Issue by fullfs** [AtomLinter/linter-sass-lint#194]
- Atom version: 1.20.1
- linter-sass-lint version: 1.8.3
- Platform: Linux

`class-name-format` in the listed below format cases Atom to freeze on file opening and saving.

.sass-lint.yml content
```
files:
  include: '**/*.scss'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  bem-depth:
    - 1
    - max-depth: 2
  border-zero:
    - 2
    - convention: 0
  brace-style:
    - 2
    - allow-single-line: false
  declarations-before-nesting:
    - 2
  class-name-format:
    - 1
    - convention: strictbem
```

scss file content
```
.n1-price-list-table__column-description_media-ads__column-description {
    padding-left: 10px;
}
```

removing `class-name-format` option solves the freezing
